/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorMoldeIdRouteImport } from './routes/editor.$moldeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorMoldeIdRoute = EditorMoldeIdRouteImport.update({
  id: '/editor/$moldeId',
  path: '/editor/$moldeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor/$moldeId': typeof EditorMoldeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor/$moldeId': typeof EditorMoldeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor/$moldeId': typeof EditorMoldeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor/$moldeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor/$moldeId'
  id: '__root__' | '/' | '/editor/$moldeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorMoldeIdRoute: typeof EditorMoldeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$moldeId': {
      id: '/editor/$moldeId'
      path: '/editor/$moldeId'
      fullPath: '/editor/$moldeId'
      preLoaderRoute: typeof EditorMoldeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorMoldeIdRoute: EditorMoldeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
