/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimuladorFutebol_masculino_3dRouteImport } from './routes/simulador/futebol_masculino_3d'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorFutebol_masculino_3dRoute =
  SimuladorFutebol_masculino_3dRouteImport.update({
    id: '/simulador/futebol_masculino_3d',
    path: '/simulador/futebol_masculino_3d',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/simulador/futebol_masculino_3d': typeof SimuladorFutebol_masculino_3dRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/simulador/futebol_masculino_3d': typeof SimuladorFutebol_masculino_3dRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/simulador/futebol_masculino_3d': typeof SimuladorFutebol_masculino_3dRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/simulador/futebol_masculino_3d'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/simulador/futebol_masculino_3d'
  id: '__root__' | '/' | '/simulador/futebol_masculino_3d'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SimuladorFutebol_masculino_3dRoute: typeof SimuladorFutebol_masculino_3dRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador/futebol_masculino_3d': {
      id: '/simulador/futebol_masculino_3d'
      path: '/simulador/futebol_masculino_3d'
      fullPath: '/simulador/futebol_masculino_3d'
      preLoaderRoute: typeof SimuladorFutebol_masculino_3dRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SimuladorFutebol_masculino_3dRoute: SimuladorFutebol_masculino_3dRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
